language: node.js
node.js: 
  - "7"
env: 
    - API_HOST_QUERY='http://10.2.65.178:3030/avatar_2017_09_js/query',
    - API_HOST_UPDATE='http://10.2.65.178:3030/avatar_2017_09_js/update',
    - DEV_PORT=9090 
  
before_install:
  - npm i -g npm@5.3.0
